# config.make generated by configure script
POCO_CONFIG = Darwin
POCO_BASE = /Users/jsg/code/gula_git/MberLinuxSDK/cpp/poco-1.4.6p4-all
POCO_BUILD = /Users/jsg/code/gula_git/MberLinuxSDK/cpp/poco-1.4.6p4-all
POCO_PREFIX = /usr/local
POCO_FLAGS = 
OMIT =  Data/ODBC Data/MySQL
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_PREFIX
export POCO_FLAGS
TESTS = 1
SAMPLES = 
